# Generated by Django 6.0.2 on 2026-02-04 17:53

import django.core.validators
import validation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Student's full name (minimum 2 characters)", max_length=100, validators=[validation.models.validate_name_length])),
                ('email', models.EmailField(help_text="Student's email address", max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('age', models.IntegerField(help_text="Student's age (15-100)", validators=[django.core.validators.MinValueValidator(15, message='Student must be at least 15 years old'), django.core.validators.MaxValueValidator(100, message='Age cannot exceed 100')])),
                ('grade', models.DecimalField(decimal_places=2, help_text="Student's grade (0.0-10.0)", max_digits=4, validators=[django.core.validators.MinValueValidator(0.0, message='Grade cannot be negative'), django.core.validators.MaxValueValidator(10.0, message='Grade cannot exceed 10.0')])),
                ('enrollment_date', models.DateField(help_text='Date of enrollment')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the student is currently active')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-enrollment_date'],
            },
        ),
    ]
